networks:
  phpinfo-2:
    internal: true
services:
  phpinfo-2:
    deploy:
      #podemos ponerlo replicated (varios contenedores en la misma vm) o global (unico contenedor x vm) 
      mode: replicated
      placement: 
        constraints:
        - node.role == worker
      replicas: 2
    expose:
    - 8080
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      #test: php -r "print file_get_contents('http://localhost:8080/');"
      test: wget -q --spider http://localhost:8080
      timeout: 1s
    image: Macarena-SRE/phpinfo-2:latest
    networks:
    - phpinfo-2
    ports:
    - 8080:8080
version: "3.8"
